app:
    conf:
        rest:
            timeout: 1500
server:
    port: 8080
    servlet:
        context-path: /between-service
spring:
    messages:
        basename: classpath:messages
    mvc:
        locale:
            default-locale: es

    application:
        name: BetweenTechApplication
    banner:
        location: banner.txt
    datasource:
        driverClassName: org.h2.Driver
        password: password
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
        username: sa
    h2:
        console:
            enabled: true
            path: /h2-console
    jackson:
        time-zone: America/Santiago
    jpa:
        hibernate:
            ddl-auto: update
    profiles:
        active: dev
